version: '2.2'
services:

  after-init:
    image: dimmsd/ubuntu-base:16.04
    command: /tmp/utils/after-init-php-fpm.sh
    environment:
      - PHP_FPM_LOG_PERMISSION=${PHP_FPM_LOG_PERMISSION}
    depends_on:
      - php-fpm
    volumes:
      - ./utils:/tmp/utils
      - ./log-fpm:/tmp/log-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        COMMIT: ${COMMIT}
    container_name: con-${FPM_IMAGE}
    image: ${FPM_IMAGE}:${UBUNTU_VERSION}.${PHP_VERSION}
    environment:
      - TIMEZONE=${TIMEZONE}
      - OWN_USER=${OWN_USER}
      - OWN_GID=${OWN_GID}
      - OWN_UID=${OWN_UID}
      - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./www:/var/www
      - ./log-xdebug:/tmp/xdebug
      - ./log-fpm:/tmp/log-fpm

